### ISSUE TITLE
General Balance from Steam user - CarltonWatkins

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Atlas-Novum#70]
-Very low liberty desire in colonial nations leading to zero independence wars.
-No successful revolutionary rebels.
-Total tech and institution parity by the end of the game. Might want to look at the mod European Centred Institutions here. It gives spread penalties based on tech groups and works very well in the base game. Might need tweaking to deal with the expanded map.

**Comment by Amazonys** [comment]
These are all great balance issues I would love to solve, but rightfully a low priority rn
