### ISSUE TITLE
Trade Companies not historical

### ISSUE THREAD

**Issue by Plutarc0** [Amazonys/Atlas-Novum#79]
Trade companies should seek to gain influence and power in the region by building trading outposts and forts, vassalizing natives either diplomatically or by force, and seizing territories.  - @Leroi6

Rough diagram here: https://cdn.discordapp.com/attachments/562106414336704533/573526401358233604/Capture.PNG

**Comment by LeRoi6** [comment]
I like the idea a lot, or at least some trade company rehash. Just commenting so I'm tied to the thread really

**Comment by Atlantispy** [comment]
I'm not a fan of trade companies being subjects, I think the existing mechanics work quite well for it, it's up to the nation to action on it.

**Comment by Plutarc0** [comment]
I think it works well too, but I can see how it fails to capture the autonomy of the British east Indian company, in particular.

Corect me if wrong, but I don't think any other trade company grew to the same extent - if so, perhaps a better way to model this would be to have something special for GBR.

**Comment by LeRoi6** [comment]
You are wrong, but I forgive you :-) Not the same extant as the British East India Company, but the VOC was close and wealthier. Almost every example of a trade company I can think of was highly autonomous at their genesis

**Comment by Plutarc0** [comment]
@LeRoi6 So from what I know of development that sounds like a really bad idea, just because the two things (charter companies and trade companies) both address the same requirement - to have non-colonial subjects that are focussed on trade. If we end up having two or more types of subjects with only slight differences between each other it will bloat the code unnecessarily and possibly confuse the users. Case in point, the protectorates mechanic that was introduced and then revoked by Paradox.

So to be frank, I would like to have trade companies be more autonomous as well, so I differ from @Atlantispy  on that regard. I can see the historical argument, and I also think they would be fun. The easiest way to get more support would be to take a branch of Amy's code and test this out to see if there are some drawbacks we are not considering - as long as we're not taking someone from doing actual necessary work (like working on the France update). Sounds fair?

**Comment by LeRoi6** [comment]
Not sure you got my idea there, I was suggesting that we could keep Trade Companies the same, and not change it into a subject. Then we would add Charter Companies as the subject type. This would make it easier to mod, in that we wouldn't have to worry about deleting the current set-up, just adding one new vassal type, and it would keep the option available for people who like the current system. You are right, two identical vassal types is a bad idea, I would not suggest that.

I wouldn't push doing now, unless you are capable then feel free.

**Comment by Plutarc0** [comment]
@LeRoi6 I understood your suggestion then - I am saying that keeping trade companies and adding charter companies as a new subject type would be a bad idea from a development point of view as they both answer the same requirement. So either we go for one or the other.

**Comment by Amazonys** [comment]
I do not want to add a trade company vassal type. I understand the desire to have certain historical trade companies to function independently, but I think that can be achieved through missions/events create colonial subjects of special tags (like a VOC tag, and many varied raj tags are planned). Frankly, the existing trade company mechanic sucks ass, but it is so hardcoded that I don't think it is worth mucking with until PDX fixes it (whenever that is). I would rather represent certain situations as either Domains (aka commonwealth nations) or colonies made through command (more specialised situations like VOC).

**Comment by Amazonys** [comment]
I am open to adjusting the discovery trade post mechanic, but I think a full rework of trade companies is off the table for the forseeable future, unless we decide to go a hacky method of reworking the regions to make more geopolitical sense. Even then that is an inelegant and potentially more frustrating adjustment.
